### ISSUE TITLE
[공지] 컴퓨터비전 걸음마 스터디 공지

### ISSUE THREAD

**Issue by unizard** [sejong-rcv/ComputerVision-Basic#1]
- 도서 관련 정보: 오일석 컴퓨터비전 https://github.com/moduPlayGround/DeepLearning-Basic/issues/14

- 스터디 일정 정보

| 일 | 월 | 화 | 수 | 목 | 금 | 토 |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 30 | 31 | 1  | 2  | 3  | 4  | 5  |
|    |    |    |    |    |  O  |    |
| 6  | 7  | 8  | 9  | 10 | 11 | 12 |
|    |  O  |    | O   |    | O   |    |
| 13  | 14  | 15  | 16  | 17 | 18 | 19 |
|    | O   |    | O   |    | O   |    |
| 20  | 21  | 22  | 23  | 24 | 25 | 26 |
|    |  O  |    |  O  |    | O   |    |
| 27  | 28  | 29  | 30  | 31 | 1 | 2 |
|    |  O  |    | O  |    |    |    |

**Comment by unizard** [comment]
1/4: 1장 소개
1/7: 2장 영상처리
1/9: 3장 에지 검출
1/11: 4장 지역 특징 검출
1/14: 5장 영상 분할
1/16: 6장 특징 기술
1/18: 7장 매칭
1/21: 8장 기계학습
1/23: 9장 인식
1/25: 10장 모션
1/28: 11장 3차원 비전
1/30: 12장 장면 이해

**Comment by unizard** [comment]
- [DeepContour: A Deep Convolutional Feature Learned by Positive-sharing Loss for Contour Detection](https://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Shen_DeepContour_A_Deep_2015_CVPR_paper.pdf), CVPR2015
  - https://github.com/shenwei1231/DeepContour, Matlab

**Comment by pk000983** [comment]
참여하겠습니다.
